# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Property.create({:property_type => "House", :address => "310 East 10th Street", :city => "Bloomington", :state => "IN", :bedrooms => "5", :baths => 2, :price => 2775, :availability => 0, :date_available => "2015-11-1", :floors => 1, :term_number => 12, :term => "months", :description => "The first floor of this house consists of a large garage that is approximately 3 cars deep. At the end of the garage is a laundry room and storage room which are heated/air conditioned. In addition to the garage, parking is available for another 2 cars at the side of the house. The main living area is located up the steps and onto the second floor. It consists of 5 bedrooms, 2 bathrooms, a kitchen, and living room. There is also a large covered porch overlooking 10th street.", :property_manager => "Buergler Properties", :phone => "812-334-1936", :ac => 1, :microwave => 0, :refrigerator => 1, :washer_dryer => 1, :dishwasher => 1, :garbage_disposal => 1, :patio_balcony => 1, :walk_in_closets => 0, :locking_room_doors => 1, :storage_space => 1, :furnished => 0, :ceiling_fans => 1, :dogs_allowed => 0, :cats_allowed => 0 })
Property.create({:property_type => "House", :address => "211 East Cottage Grove Avenue", :city => "Bloomington", :state => "IN", :bedrooms => "3", :baths => 2, :price => 1170, :availability => 0, :date_available => "2015-11-18", :floors => 1, :term_number => 12, :term => "months"})
Property.create({:property_type => "House", :address => "417 East 10th Street", :city => "Bloomington", :state => "IN", :bedrooms => "4", :baths => 2, :price => 3000, :availability => 1, :floors => 2})
Property.create({:property_type => "Apartment", :address => "500 South Park Ridge Road", :city => "Bloomington", :state => "IN", :bedrooms => "2, 3", :baths => 2, :price => 1170, :price_two => 1600, :availability => 0, :date_available => "2015-11-18", :floors => 1, :term_number => 12, :term => "months"})

Dorm.create({:name => "Forest", :lat => 39.164757, :lng => -86.512474, :location => "Southeast", :phone => "812-855-5311", :email => "foresctr@indiana.edu", :address => "1725 East Third Street Bloomington, IN 47406-7509", :dorm_type => "Dorm", :floors => 11, :beds => "Down, Bunked", :rooms => "Single, Double", :bathrooms => "Community", :gender_on_floor => "Single, Split Gender", :description => "This residence hall is comprised of two 11-story towers connected by a center building. The center building includes resident mailboxes, a help desk, computer lab, dining hall, lounge, and much more. Forest has recently been renovated to add new dining, \"The Restaurants at Woodland\". This is Indiana University's newest dining option and consists of nine micro restaurants.", :price => "Average", :parking_zone => "D1", :academic_support_center => 1, :computer_lab => 1, :library => 0, :ud_academic_advising => 1, :ac => 1, :carpet_in_room => 1, :dining_onsite => 1, :music_practice_room => 1, :piano => 1, :dance_studio => 1, :exercise_room => 0, :game_room => 1, :laundry_on_floor => 0, :laundry_ground_floor => 1, :quiet_study_area => 1, :community_kitchen => 0, :iu_secure_wifi => 1})
